### ISSUE TITLE
cannot upgrade to 0.5.0 SHA256 mismatch

### ISSUE THREAD

**Issue by opichon** [trufae/Therm#72]
When trying to upgrade from 0.4.2 to 0.5.0 via homebrew I get an error `SHA256 mismatch`. See full output below.

```
❯ brew upgrade therm
==> Upgrading 1 outdated package:
therm 0.4.2 -> 0.5.0
==> Upgrading therm
==> Downloading https://github.com/trufae/Therm/releases/download/0.5.0/Therm-0.5.0.zip
Already downloaded: /Users/olivier/Library/Caches/Homebrew/downloads/15e010be41cd23be53a6159dfba2f8f9e1eec2f87910db174707a0eaba1600be--Therm-0.5.0.zip
==> Purging files for version 0.5.0 of Cask therm
Error: therm: SHA256 mismatch
Expected: c83ab68524cc0f60b57672e06026f1e2d7481e7e6aadd28402f2f0a587686f7f
  Actual: 5e2271d077f08aa084a2107b02d546363746ab21b07bcea1ccd286554deaf930
    File: /Users/olivier/Library/Caches/Homebrew/downloads/15e010be41cd23be53a6159dfba2f8f9e1eec2f87910db174707a0eaba1600be--Therm-0.5.0.zip
To retry an incomplete download, remove the file above.
```

**Comment by trufae** [comment]
I dont maintain the brew package

**Comment by opichon** [comment]
Do you know how does?

**Comment by opichon** [comment]
I found this: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/therm.rb.
However, it seems you haven't published the checksum for the 0.5.0 release. Could you do that? I'll post a fix in homebrew.

**Comment by trufae** [comment]
Sorry i was busy with other stuff, i just pushed the sha256 and confirmed this is the same hash of the build i did in my local machine. Check the release page, But im dropping the checksum in here just in case.

i'm not a big fan of publishing checksums in the same site as the builds itself. as it doesnt provide any trust because if someone takes over my account they can modify the artifacts and the messages with the checksum.

Ideally homebrew should be doing and publishing their own builds of Therm instead of relying on blobs.

**Comment by trufae** [comment]
Thanks for taking care on fixing the formula
